name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-07-20
          components: rustfmt
          override: true

      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: doc
